//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JazzCoffe
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChamCong
    {
        public int MaCC { get; set; }
        public string MaNV { get; set; }
        public System.DateTime NgayLam { get; set; }
        public Nullable<System.TimeSpan> GioVao { get; set; }
        public Nullable<System.TimeSpan> GioRa { get; set; }
        public Nullable<decimal> SoGioLam { get; set; }
        public string TrangThai { get; set; }
        public string GhiChu { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
