//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JazzCoffe
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuNhap
    {
        public int MaPN { get; set; }
        public int MaNL { get; set; }
        public double SoLuongNhap { get; set; }
        public decimal DonGiaNhap { get; set; }
    
        public virtual NguyenLieu NguyenLieu { get; set; }
        public virtual PhieuNhapKho PhieuNhapKho { get; set; }
    }
}
