//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JazzCoffe
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoUong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DoUong()
        {
            this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();
            this.CongThucDoUongs = new HashSet<CongThucDoUong>();
        }
    
        public string MaDU { get; set; }
        public string TenDU { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public Nullable<decimal> DonGia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        public virtual LoaiDoUong LoaiDoUong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CongThucDoUong> CongThucDoUongs { get; set; }
    }
}
